"""create images on the buisness

Revision ID: 4f6bbc523641
Revises: adf7018ea399
Create Date: 2025-09-17 14:33:12.314124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6bbc523641'
down_revision: Union[str, Sequence[str], None] = 'adf7018ea399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Buisness', sa.Column('image', sa.String(), nullable=True))
    op.create_index(op.f('ix_Buisness_image'), 'Buisness', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Buisness_image'), table_name='Buisness')
    op.drop_column('Buisness', 'image')
    # ### end Alembic commands ###
