"""create options with nullabale options

Revision ID: a56a54551ceb
Revises: 4f6bbc523641
Create Date: 2025-09-17 20:14:06.697304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56a54551ceb'
down_revision: Union[str, Sequence[str], None] = '4f6bbc523641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Buisness', sa.Column('image', sa.String(), nullable=True))
    op.create_index(op.f('ix_Buisness_image'), 'Buisness', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Buisness_image'), table_name='Buisness')
    op.drop_column('Buisness', 'image')
    # ### end Alembic commands ###
