"""Tables of mesas y producsts

Revision ID: a58b45483d86
Revises: a56a54551ceb
Create Date: 2025-09-20 11:20:01.901148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58b45483d86'
down_revision: Union[str, Sequence[str], None] = 'a56a54551ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['Buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    op.create_table('Tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['Buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tables_capacity'), 'Tables', ['capacity'], unique=False)
    op.create_index(op.f('ix_Tables_id'), 'Tables', ['id'], unique=False)
    op.create_index(op.f('ix_Tables_location'), 'Tables', ['location'], unique=False)
    op.create_index(op.f('ix_Tables_name'), 'Tables', ['name'], unique=True)
    op.create_index(op.f('ix_Tables_status'), 'Tables', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tables_status'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_name'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_location'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_id'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_capacity'), table_name='Tables')
    op.drop_table('Tables')
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
