"""create roles and users tables

Revision ID: adf7018ea399
Revises: 0a20e2aa80bf
Create Date: 2025-09-17 10:00:24.110224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf7018ea399'
down_revision: Union[str, Sequence[str], None] = '0a20e2aa80bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.add_column('Buisness', sa.Column('address', sa.String(), nullable=True))
    op.add_column('Buisness', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('Buisness', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_Buisness_address'), 'Buisness', ['address'], unique=False)
    op.create_index(op.f('ix_Buisness_email'), 'Buisness', ['email'], unique=True)
    op.create_index(op.f('ix_Buisness_phone'), 'Buisness', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Buisness_phone'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_email'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_address'), table_name='Buisness')
    op.drop_column('Buisness', 'email')
    op.drop_column('Buisness', 'phone')
    op.drop_column('Buisness', 'address')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('users_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
