"""create licencia and buisness tables

Revision ID: b6ed4da36f77
Revises: 226e7aa56cd9
Create Date: 2025-09-22 11:23:22.644881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ed4da36f77'
down_revision: Union[str, Sequence[str], None] = '226e7aa56cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licencia_id'), 'licencia', ['id'], unique=False)
    op.create_index(op.f('ix_licencia_name'), 'licencia', ['name'], unique=True)
    op.create_table('buisness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capital_money', sa.Integer(), nullable=True),
    sa.Column('licencia_id', sa.Integer(), nullable=True),
    sa.Column('permisos', sa.String(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buisness_address'), 'buisness', ['address'], unique=False)
    op.create_index(op.f('ix_buisness_capital_money'), 'buisness', ['capital_money'], unique=False)
    op.create_index(op.f('ix_buisness_email'), 'buisness', ['email'], unique=True)
    op.create_index(op.f('ix_buisness_id'), 'buisness', ['id'], unique=False)
    op.create_index(op.f('ix_buisness_name'), 'buisness', ['name'], unique=True)
    op.create_index(op.f('ix_buisness_permisos'), 'buisness', ['permisos'], unique=False)
    op.create_index(op.f('ix_buisness_phone'), 'buisness', ['phone'], unique=False)
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    op.create_table('Tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tables_capacity'), 'Tables', ['capacity'], unique=False)
    op.create_index(op.f('ix_Tables_id'), 'Tables', ['id'], unique=False)
    op.create_index(op.f('ix_Tables_location'), 'Tables', ['location'], unique=False)
    op.create_index(op.f('ix_Tables_name'), 'Tables', ['name'], unique=True)
    op.create_index(op.f('ix_Tables_status'), 'Tables', ['status'], unique=False)
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_image'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('Products')
    op.drop_table('Business')
    op.drop_table('Licence')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('Licence',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Licencia_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Licencia_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Business',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Buisness_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capital_money', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('licencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permisos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['Licence.id'], name='Buisness_licencia_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Buisness_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buisness_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['Business.id'], name=op.f('Product_buisness_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Product_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('users_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_image'), 'users', ['image'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.drop_index(op.f('ix_Tables_status'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_name'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_location'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_id'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_capacity'), table_name='Tables')
    op.drop_table('Tables')
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_table('Product')
    op.drop_index(op.f('ix_buisness_phone'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_permisos'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_name'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_id'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_email'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_capital_money'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_address'), table_name='buisness')
    op.drop_table('buisness')
    op.drop_index(op.f('ix_licencia_name'), table_name='licencia')
    op.drop_index(op.f('ix_licencia_id'), table_name='licencia')
    op.drop_table('licencia')
    # ### end Alembic commands ###
