services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  inventory-service:
    build: ./inventory
    container_name: inventory_service
    restart: always
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./inventory:/app

  orders-service:
    build: ./orders
    container_name: orders_service
    restart: always
    env_file:
      - .env
    ports:
      - "8003:8000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./orders:/app

volumes:
  postgres_data:
  rabbitmq_data:
