services:
  gateway:
    build: .
    container_name: backend_gateway_service
    restart: always
    env_file:
      - .env
    ports:
      - "8005:8000"
    depends_on:
      - usuarios-service
      - buisness-service
      - inventory-service
      - orders-service
      - rents-service
      - landlord-service
    volumes:
      - ./gateways.py:/app/gateways.py
      - ./common:/app/common
    networks:
      - backend-network

  postgres:
    image: postgres:15
    container_name: backend_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: backend_rabbitmq
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend-network

  usuarios-service:
    build:
      context: .
      dockerfile: ./usuarios/Dockerfile
    container_name: backend_usuarios_service
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./usuarios:/app/usuarios
      - ./common:/app/common
    networks:
      - backend-network

  buisness-service:
    build:
      context: .
      dockerfile: ./buisness/Dockerfile
    container_name: backend_buisness_service
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./buisness:/app/buisness
      - ./common:/app/common
    networks:
      - backend-network

  inventory-service:
    build:
      context: .
      dockerfile: ./inventory/Dockerfile
    container_name: backend_inventory_service
    restart: always
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./inventory:/app/inventory
      - ./common:/app/common
    networks:
      - backend-network

  orders-service:
    build:
      context: .
      dockerfile: ./orders/Dockerfile
    container_name: backend_orders_service
    restart: always
    env_file:
      - .env
    ports:
      - "8003:8003"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./orders:/app/orders
      - ./common:/app/common
    networks:
      - backend-network

  rents-service:
    build:
      context: .
      dockerfile: ./rentas/Dockerfile
    container_name: backend_rents_service
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8004:8004"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./rentas:/app/rentas
      - ./common:/app/common
    networks:
      - backend-network

  landlord-service:
    build:
      context: .
      dockerfile: ./landlord/Dockerfile
    container_name: backend_landlord_service
    restart: always
    env_file:
      - .env
    ports:
      - "8006:8006"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./landlord:/app/landlord
      - ./common:/app/common
    networks:
      - backend-network

  realtime-service:
    build: ./realtime
    container_name: backend_realtime_service
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rents-service
    volumes:
      - ./realtime:/app
    networks:
      - backend-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  backend-network:
    driver: bridge
