"""create images on the user

Revision ID: 454cc552365b
Revises: abcd1234efgh
Create Date: 2025-09-17 14:39:40.836185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454cc552365b'
down_revision: Union[str, Sequence[str], None] = 'abcd1234efgh'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_image'), 'users', ['image'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_Licencia_id'), table_name='Licencia')
    op.drop_index(op.f('ix_Licencia_name'), table_name='Licencia')
    op.drop_table('Licencia')
    op.drop_index(op.f('ix_Buisness_address'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_capital_money'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_categoria'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_email'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_id'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_name'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_permisos'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_phone'), table_name='Buisness')
    op.drop_table('Buisness')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buisness',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capital_money', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('licencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permisos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['Licencia.id'], name=op.f('Buisness_licencia_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Buisness_pkey'))
    )
    op.create_index(op.f('ix_Buisness_phone'), 'Buisness', ['phone'], unique=False)
    op.create_index(op.f('ix_Buisness_permisos'), 'Buisness', ['permisos'], unique=False)
    op.create_index(op.f('ix_Buisness_name'), 'Buisness', ['name'], unique=True)
    op.create_index(op.f('ix_Buisness_id'), 'Buisness', ['id'], unique=False)
    op.create_index(op.f('ix_Buisness_email'), 'Buisness', ['email'], unique=True)
    op.create_index(op.f('ix_Buisness_categoria'), 'Buisness', ['categoria'], unique=False)
    op.create_index(op.f('ix_Buisness_capital_money'), 'Buisness', ['capital_money'], unique=False)
    op.create_index(op.f('ix_Buisness_address'), 'Buisness', ['address'], unique=False)
    op.create_table('Licencia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Licencia_pkey'))
    )
    op.create_index(op.f('ix_Licencia_name'), 'Licencia', ['name'], unique=True)
    op.create_index(op.f('ix_Licencia_id'), 'Licencia', ['id'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_image'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
