"""init schema

Revision ID: cabd99173abb
Revises: 
Create Date: 2025-09-20 13:28:14.356642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabd99173abb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_image'), 'users', ['image'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.drop_index(op.f('ix_Buisness_address'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_capital_money'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_categoria'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_email'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_id'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_image'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_name'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_permisos'), table_name='Buisness')
    op.drop_index(op.f('ix_Buisness_phone'), table_name='Buisness')
    op.rename_table("Buisness", "Business")
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.rename_table("Product", "Products")
    op.drop_index(op.f('ix_Licencia_id'), table_name='Licencia')
    op.drop_index(op.f('ix_Licencia_name'), table_name='Licencia')
    op.rename_table("Licencia", "Licence")
    op.drop_index(op.f('ix_Tables_capacity'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_id'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_location'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_name'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_status'), table_name='Tables')
    op.drop_table('Tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buisness_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['Buisness.id'], name=op.f('Tables_buisness_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Tables_pkey'))
    )
    op.create_index(op.f('ix_Tables_status'), 'Tables', ['status'], unique=False)
    op.create_index(op.f('ix_Tables_name'), 'Tables', ['name'], unique=True)
    op.create_index(op.f('ix_Tables_location'), 'Tables', ['location'], unique=False)
    op.create_index(op.f('ix_Tables_id'), 'Tables', ['id'], unique=False)
    op.create_index(op.f('ix_Tables_capacity'), 'Tables', ['capacity'], unique=False)
    op.create_table('Licencia',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Licencia_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Licencia_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_Licencia_name'), 'Licencia', ['name'], unique=True)
    op.create_index(op.f('ix_Licencia_id'), 'Licencia', ['id'], unique=False)
    op.create_table('Product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buisness_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['Buisness.id'], name=op.f('Product_buisness_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Product_pkey'))
    )
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_table('Buisness',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capital_money', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('licencia_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permisos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['Licencia.id'], name=op.f('Buisness_licencia_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('Buisness_pkey'))
    )
    op.create_index(op.f('ix_Buisness_phone'), 'Buisness', ['phone'], unique=False)
    op.create_index(op.f('ix_Buisness_permisos'), 'Buisness', ['permisos'], unique=False)
    op.create_index(op.f('ix_Buisness_name'), 'Buisness', ['name'], unique=True)
    op.create_index(op.f('ix_Buisness_image'), 'Buisness', ['image'], unique=False)
    op.create_index(op.f('ix_Buisness_id'), 'Buisness', ['id'], unique=False)
    op.create_index(op.f('ix_Buisness_email'), 'Buisness', ['email'], unique=True)
    op.create_index(op.f('ix_Buisness_categoria'), 'Buisness', ['categoria'], unique=False)
    op.create_index(op.f('ix_Buisness_capital_money'), 'Buisness', ['capital_money'], unique=False)
    op.create_index(op.f('ix_Buisness_address'), 'Buisness', ['address'], unique=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_image'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
