"""add sold to products

Revision ID: 3e452cdc72cb
Revises: 8184cdc7c13b
Create Date: 2026-01-27 12:08:02.691518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e452cdc72cb'
down_revision: Union[str, Sequence[str], None] = '8184cdc7c13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_buisness_id'), 'Product', ['buisness_id'], unique=False)
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_sold'), 'Product', ['sold'], unique=False)
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.drop_index(op.f('ix_Product_sold'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_index(op.f('ix_Product_buisness_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
