"""create migration initial

Revision ID: 45bc09c0693e
Revises: 
Create Date: 2025-11-12 21:28:45.866702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bc09c0693e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('buisness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capital_money', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buisness_address'), 'buisness', ['address'], unique=False)
    op.create_index(op.f('ix_buisness_capital_money'), 'buisness', ['capital_money'], unique=False)
    op.create_index(op.f('ix_buisness_email'), 'buisness', ['email'], unique=True)
    op.create_index(op.f('ix_buisness_id'), 'buisness', ['id'], unique=False)
    op.create_index(op.f('ix_buisness_name'), 'buisness', ['name'], unique=True)
    op.create_index(op.f('ix_buisness_phone'), 'buisness', ['phone'], unique=False)
    op.create_index(op.f('ix_buisness_user_id'), 'buisness', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_image'), 'users', ['image'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    op.create_table('Tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buisness_id'], ['buisness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tables_capacity'), 'Tables', ['capacity'], unique=False)
    op.create_index(op.f('ix_Tables_id'), 'Tables', ['id'], unique=False)
    op.create_index(op.f('ix_Tables_location'), 'Tables', ['location'], unique=False)
    op.create_index(op.f('ix_Tables_name'), 'Tables', ['name'], unique=True)
    op.create_index(op.f('ix_Tables_status'), 'Tables', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tables_status'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_name'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_location'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_id'), table_name='Tables')
    op.drop_index(op.f('ix_Tables_capacity'), table_name='Tables')
    op.drop_table('Tables')
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_table('Product')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_image'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_buisness_user_id'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_phone'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_name'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_id'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_email'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_capital_money'), table_name='buisness')
    op.drop_index(op.f('ix_buisness_address'), table_name='buisness')
    op.drop_table('buisness')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
