"""Remove inputs from products

Revision ID: 8184cdc7c13b
Revises: f90b77304218
Create Date: 2026-01-14 17:15:48.482572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8184cdc7c13b'
down_revision: Union[str, Sequence[str], None] = 'f90b77304218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('buisness_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Product_buisness_id'), 'Product', ['buisness_id'], unique=False)
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=False)
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_index(op.f('ix_Product_price'), 'Product', ['price'], unique=False)
    op.create_index(op.f('ix_Product_stock'), 'Product', ['stock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_stock'), table_name='Product')
    op.drop_index(op.f('ix_Product_price'), table_name='Product')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_index(op.f('ix_Product_buisness_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
