"""Remove inputs from products

Revision ID: f90b77304218
Revises: 45bc09c0693e
Create Date: 2026-01-14 17:13:50.003526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90b77304218'
down_revision: Union[str, Sequence[str], None] = '45bc09c0693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licencia_id'), table_name='licencia')
    op.drop_index(op.f('ix_licencia_name'), table_name='licencia')
    op.drop_table('licencia')
    op.create_index(op.f('ix_Product_buisness_id'), 'Product', ['buisness_id'], unique=False)
    op.drop_constraint(op.f('Product_buisness_id_fkey'), 'Product', type_='foreignkey')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(op.f('Product_buisness_id_fkey'), 'Product', 'buisness', ['buisness_id'], ['id'])
    op.drop_index(op.f('ix_Product_buisness_id'), table_name='Product')
    op.create_table('licencia',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('licencia_pkey'))
    )
    op.create_index(op.f('ix_licencia_name'), 'licencia', ['name'], unique=True)
    op.create_index(op.f('ix_licencia_id'), 'licencia', ['id'], unique=False)
    # ### end Alembic commands ###
